run: 
	./z.out input.txt
	
a:
	g++ -std=c++17 -O2 -o z.out a.cpp
	./z.out input.txt

b:
	g++ -std=c++17 -O2 -o z.out b.cpp
	./z.out input.txt

c:
	g++ -std=c++17 -O2 -o z.out c.cpp
	./z.out input.txt

d:
	g++ -std=c++17 -O2 -o z.out d.cpp
	./z.out input.txt

e:
	g++ -std=c++17 -O2 -o z.out e.cpp
	./z.out input.txt

f:
	g++ -std=c++17 -O2 -o z.out f.cpp
	./z.out input.txt

c2:
	g++ -std=c++17 -O2 -o z.out c2.cpp
	./z.out input.txt

d2:
	g++ -std=c++17 -O2 -o z.out d2.cpp
	./z.out input.txt