run:
	clear
	./z.out input.txt
	
a:
	clear
	g++ -std=c++17 -O2 -o z.out a.cpp
	./z.out input.txt

b:	
	clear
	g++ -std=c++17 -O2 -o z.out b.cpp
	./z.out input.txt

c:
	clear
	g++ -std=c++17 -O2 -o z.out c.cpp
	./z.out input.txt

d:
	g++ -std=c++17 -O2 -o z.out d.cpp
	./z.out input.txt

e:
	g++ -std=c++17 -O2 -o z.out e.cpp
	./z.out input.txt

f:
	g++ -std=c++17 -O2 -o z.out f.cpp
	./z.out input.txt

a2:
	clear
	g++ -std=c++17 -O2 -o z.out a2.cpp
	./z.out input.txt

b2:
	clear
	g++ -std=c++17 -O2 -o z.out b2.cpp
	./z.out input.txt

c2:
	clear
	g++ -std=c++17 -O2 -o z.out c2.cpp
	./z.out input.txt

d2:
	clear
	g++ -std=c++17 -O2 -o z.out d2.cpp
	./z.out input.txt

e2:
	clear
	g++ -std=c++17 -O2 -o z.out e2.cpp
	./z.out input.txt

f2:
	clear
	g++ -std=c++17 -O2 -o z.out f2.cpp
	./z.out input.txt